name: Build PDF

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    name: Build PDF
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get install make latexmk texlive texlive-latex-extra

      - name: Build PDF
        run: |
          make

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: pdf
          path: build/main.pdf

      - name: Update 'latest' tag
        uses: richardsimko/update-tag@v1
        with:
          tag_name: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Rolling Release
        run: |
          gh release delete latest -y || true
          gh release create latest -p -t "Automatic build" -n "Automatic build for commit ${GITHUB_SHA}" build/main.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
